// https://developer.apple.com/documentation/applicationservices/axnotificationconstants_h/miscellaneous_defines
// AXNotificationConstants.h:1

public enum AXNotification: String, Sendable {
  case mainWindowChanged = "AXMainWindowChanged"
  case focusedWindowChanged = "AXFocusedWindowChanged"
  case focusedUIElementChanged = "AXFocusedUIElementChanged"
  case applicationActivated = "AXApplicationActivated"
  case applicationDeactivated = "AXApplicationDeactivated"
  case applicationHidden = "AXApplicationHidden"
  case applicationShown = "AXApplicationShown"
  case windowCreated = "AXWindowCreated"
  case windowMoved = "AXWindowMoved"
  case windowResized = "AXWindowResized"
  case windowMiniaturized = "AXWindowMiniaturized"
  case windowDeminiaturized = "AXWindowDeminiaturized"
  case drawerCreated = "AXDrawerCreated"
  case sheetCreated = "AXSheetCreated"
  case helpTagCreated = "AXHelpTagCreated"
  case valueChanged = "AXValueChanged"
  case uiElementDestroyed = "AXUIElementDestroyed"
  case elementBusyChanged = "AXElementBusyChanged"
  case menuOpened = "AXMenuOpened"
  case menuClosed = "AXMenuClosed"
  case menuItemSelected = "AXMenuItemSelected"
  case rowCountChanged = "AXRowCountChanged"
  case rowExpanded = "AXRowExpanded"
  case rowCollapsed = "AXRowCollapsed"
  case selectedCellsChanged = "AXSelectedCellsChanged"
  case unitsChanged = "AXUnitsChanged"
  case selectedChildrenMoved = "AXSelectedChildrenMoved"
  case selectedChildrenChanged = "AXSelectedChildrenChanged"
  case resized = "AXResized"
  case moved = "AXMoved"
  case created = "AXCreated"
  case selectedRowsChanged = "AXSelectedRowsChanged"
  case selectedColumnsChanged = "AXSelectedColumnsChanged"
  case selectedTextChanged = "AXSelectedTextChanged"
  case titleChanged = "AXTitleChanged"
  case layoutChanged = "AXLayoutChanged"
  case announcementRequested = "AXAnnouncementRequested"
  case uiElementsKey = "AXUIElementsKey"
  case priorityKey = "AXPriorityKey"
  case announcementKey = "AXAnnouncementKey"
  case uiElementTitleKey = "AXUIElementTitleKey"
}
