public enum Role: String {
  case button = "AXButton"
  case cell = "AXCell"
  case checkBox = "AXCheckBox"
  case comboBox = "AXComboBox"
  case image = "AXImage"
  case incrementor = "AXIncrementor"
  case list = "AXList"
  case menuButton = "AXMenuButton"
  case menuItem = "AXMenuItem"
  case outline = "AXOutline"
  case popUpButton = "AXPopUpButton"
  case radioButton = "AXRadioButton"
  case row = "AXRow"
  case slider = "AXSlider"
  case staticText = "AXStaticText"
  case table = "AXTable"
  case textArea = "AXTextArea"
  case textField = "AXTextField"
  case window = "AXWindow"
}
