// swiftformat:disable organizeDeclarations
public enum SubRole: String, Sendable {
  case applicationDockItem = "AXApplicationDockItem"
  case closeButton = "AXCloseButton"
  case contentList = "AXContentList"
  case decrementArrow = "AXDecrementArrow"
  case decrementPage = "AXDecrementPage"
  case definitionList = "AXDefinitionList"
  case descriptionList = "AXDescriptionList"
  case dialog = "AXDialog"
  case dockExtraDockItem = "AXDockExtraDockItem"
  case documentDockItem = "AXDocumentDockItem"
  case floatingWindow = "AXFloatingWindow"
  case folderDockItem = "AXFolderDockItem"
  case fullScreenButton = "AXFullScreenButton"
  case incrementArrow = "AXIncrementArrow"
  case incrementPage = "AXIncrementPage"
  case minimizeButton = "AXMinimizeButton"
  case minimizedWindowDockItem = "AXMinimizedWindowDockItem"
  case outlineRow = "AXOutlineRow"
  case processSwitcherList = "AXProcessSwitcherList"
  case ratingIndicator = "AXRatingIndicator"
  case searchField = "AXSearchField"
  case secureTextField = "AXSecureTextField"
  case separatorDockItem = "AXSeparatorDockItem"
  case sortButton = "AXSortButton"
  case standardWindow = "AXStandardWindow"
  case `switch` = "AXSwitch"
  case systemDialog = "AXSystemDialog"
  case systemFloatingWindow = "AXSystemFloatingWindow"
  case tableRow = "AXTableRow"
  case textAttachment = "AXTextAttachment"
  case textLink = "AXTextLink"
  case timeline = "AXTimeline"
  case toggle = "AXToggle"
  case toolbarButton = "AXToolbarButton"
  case trashDockItem = "AXTrashDockItem"
  case URLDockItem = "AXURLDockItem"
  case unknown = "AXUnknown"
  case zoomButton = "AXZoomButton"

  // MARK: - Undocumented

  case collectionList = "AXCollectionList"
  case decorative = "AXDecorative"
  case menuBarExtra = "AXMenuExtra"
  case notificationCenterBanner = "AXNotificationCenterBanner"
  case sectionList = "AXSectionList"
  case suggestion = "AXSuggestion"
  case tabButton = "AXTabButton"
}

// swiftformat:enable organizeDeclarations
